// <auto-generated />
using System;
using Forum.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forum.Infrastructure.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    partial class ForumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Forum.Infrastructure.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0164f0f3-f21c-42cf-98ec-6f4b4cbd1aee"),
                            Content = "My first post will be about performing CRUD operations in MVC. It is so mutch fun! I love it. I love EF CORE",
                            Title = "My first post"
                        },
                        new
                        {
                            Id = new Guid("004b15fe-536d-4526-808a-6d0d8d31db3b"),
                            Content = "The Second post will also be about performing CRUD operations in MVC. It is so mutch fun! I adore it! I love aspNetCore",
                            Title = "My second post"
                        },
                        new
                        {
                            Id = new Guid("c4844444-7cc2-4903-8de4-98747ed9fa95"),
                            Content = "Hello! It is so mutch fun! My third post will be about performing CRUD operations in MVC YAY. It is so mutch fun!",
                            Title = "My third"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
